services:
  - type: web
    name: mmuconnect-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myapp.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: mmuconnect-db
          property: connectionString
    autoDeploy: true

databases:
  - name: mmuconnect-db
    databaseName: mmuconnect
    user: mmuconnectuser
