services:
  - type: web
    name: mmuconnect-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn MMUConnect.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
    autoDeploy: true

databases:
  - name: mmuconnect-db
    databaseName: mmuconnect
    user: mmuconnectuser
