# Generated by Django 5.2 on 2025-04-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='self_bio',
            field=models.TextField(default='No bio available'),
        ),
    ]
