# Generated by Django 5.2 on 2025-05-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_author_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='faculty',
            field=models.CharField(choices=[('FCI', 'Faculty of Computing'), ('FOE', 'Faculty of Engineering'), ('FCM', 'Faculty of Creative Multimedia'), ('FOM', 'Faculty of Management'), ('FAC', 'Faculty of Applied Comm'), ('Not specified', 'Default')], default='Not specified', max_length=20),
        ),
    ]
