# Generated by Django 5.2 on 2025-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_author_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('Unknown Gender', 'Unknown Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Unknown Gender', max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='faculty',
            field=models.CharField(choices=[('Not specified', 'Default'), ('FCI', 'Faculty of Computing'), ('FOE', 'Faculty of Engineering'), ('FCM', 'Faculty of Creative Multimedia'), ('FOM', 'Faculty of Management'), ('FAC', 'Faculty of Applied Comm')], default='Not specified', max_length=20),
        ),
    ]
