# Generated by Django 5.2 on 2025-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_author_gender_alter_author_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='author_images/default.jpg', upload_to='author_images/'),
        ),
    ]
