# Generated by Django 5.2 on 2025-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='https://res.cloudinary.com/your_cloud/image/upload/author_images/default.jpg', upload_to='author_images/'),
        ),
    ]
