# Generated by Django 5.2 on 2025-06-02 13:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='author_images/default.jpg', max_length=255),
        ),
    ]
