# Generated by Django 5.2 on 2025-06-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_author_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
