# Generated by Django 5.2 on 2025-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('mood', 'Mood'), ('studies', 'Studies')], default='mood', max_length=10),
        ),
    ]
